//! Raw FFI bindings to librtlsdr, generated by bindgen at build time.
//!
//! Nothing here is safe. Use the `rtlsdr` crate instead.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
