[package]
name = "nodes"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
dsp.workspace = true
pipeline.workspace = true
decode.workspace = true
rayon.workspace = true

[dev-dependencies]
sources.workspace = true

[[example]]
name = "chain"

[[example]]
name = "bench"

[[example]]
name = "split"
